### ISSUE TITLE
support dispatch-http

### ISSUE THREAD

**Issue by softprops** [ornicar/scalex#14]
I love this. It would be awesome if you could add support for the dispatch http. I could help if you point me in the right direction

**Comment by ornicar** [comment]
what is "distpatch http"?

**Comment by softprops** [comment]
Only the most awesome http client for scala ever

https://github.com/n8han/databinder-dispatch
http://dispatch.databinder.net/

The reason I suggested it was because of its heavy use of symbolic method names. Something like your search engine seems like it would really help a lot of people out.

**Comment by ornicar** [comment]
unfortunately, I cannot index it at the moment because it has dependencies to other libraries.
