### ISSUE TITLE
Issues with formatting

### ISSUE THREAD

**Issue by PhiLhoSoft** [ornicar/scalex#2]
Looks like you interpret too much when parsing the doc. comments. Or maybe the formatting of these comments isn't consistent!
Example: search 'breakOut'
There is a pink/salmon highlight because author used single quotes. Which is probably common.
Mmm, I see it is working when there is only one such quoted word in the description... Or other cases (searching 'view'). Is it related to the usage of parentheses in the given example?

Side note: if I type 'break', I don't see 'breakOut', which is displayed when I add a 'O'.

**Comment by ornicar** [comment]
The comment formatting of `breakOut` is wrong. Scaladoc also gets wrong html:

```
<p>Provides a CanBuildFrom instance that builds a specific target collection (<code>To')
 irrespective of the original collection (</code>From').
</p>
```

The problem is in the quotes used in the comment:

```
/** Provides a CanBuildFrom instance that builds a specific target collection (`To')
 *  irrespective of the original collection (`From').
 */
```

As for the search thing, I know it's not optimal for now. It's just mongodb regex queries. Should be more precise once I move it to elasticsearch :)

**Comment by PhiLhoSoft** [comment]
Ah, that's this bad (IMHO) habit of using backquotes as opening quotes!
So indeed the issue is with the comment writing, which is a common issue, I fear... :-)
Glad it was a false alarm (for your code).
