### ISSUE TITLE
multi-argument type constructors

### ISSUE THREAD

**Issue by retronym** [ornicar/scalex#22]
query: `: List[Either[A, B]] => (List[A], List[B])`

result:

```
[1.31] failure: `)' expected but `,' found



List[Either[A, B]] => (List[A], List[B])

                              ^
```

**Comment by ornicar** [comment]
Fixed, will be included in the next deploy.

Btw I found no function matching `List[Either[A, B]] => (List[A], List[B])`.

But `list[a] => (a => boolean) => (list[a], list[a])` finds `partition` and `span` as expected.

**Comment by retronym** [comment]
The example was trying to search for `List.separate`. Actually, I can't find that by name in Scalex.

```
@deprecated
def
separate [A, B] (es: Iterable[Either[A, B]]): (List[A], List[B])
```

**Comment by ornicar** [comment]
ah, it's because it's deprecated. I don't index deprecated methods.

**Comment by ornicar** [comment]
and it's a mistake. I will have them indexed back.
