### ISSUE TITLE
links to Predef scaladoc 400

### ISSUE THREAD

**Issue by gtani7** [ornicar/scalex#29]
This is an example query on (<%<)

http://scalex.org/?q=%3C%25%3C
http://scalex.org/?q=%3C%25%3C#scalaPredefreadResolveAnyRef

This is link that 400's

http://www.scala-lang.org/api/current/scala/Predef/%3C%%3C.html

---

Easy default link: 

https://github.com/scala/scala/blob/master/src/library/scala/Predef.scala

**Comment by ornicar** [comment]
fixed, thanks
