### ISSUE TITLE
help with ENSIME migration/integration

### ISSUE THREAD

**Issue by fommil** [ornicar/scalex#47]
Thank you for creating this great project!

We'd love to have an embedded scalex-like search engine in ENSIME

  https://github.com/ensime/ensime-server/issues/472

We're already parsing the classfiles of everything on the user's classpath with ASM and the de-pickler.

Would you be interested in helping us out to effectively create a minimal library version of scalex? (probably in the ENSIME codebase, but if you can define it abstractly in a library in terms of data providers that would also work).

Scalex itself has a lot of code related to your persistence and serving results over HTTP. I'm really just looking for something that takes a user's raw query and converts it into a semantic query that we could run over some database schema (e.g. SQL or lucene or a combination of the two).

**Comment by ornicar** [comment]
Sorry, I don't maintain scalex anymore. Good luck with your thing!
